name: Lets Start 
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "Sam Manekshaw"
          replace: "Emcee"
      - name: Pull All Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Haguromo✨✨'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: satyanandatripathi
          commit_user_email: lds3sp0rts@gmail.com
